### ISSUE TITLE
Privacy Policy on Login Page Can't be Closed

### ISSUE THREAD

**Issue by NickMcGettigan** [steven2030/Autama-Backend#8]
**Describe the bug**
Privacy Policy on Login Page Can't be Closed

**To Reproduce**
1. Go to login page
2. Click on the x with the privacy policy
3. Nothing happens

**Expected behavior**
Either make the X and privacy policy clickable or don't display on that page.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 81.0.4044.122 (Official Build) (64-bit)

**Comment by ryjonespdx** [comment]
Thanks Nick, fixed! I moved the cookie banner <div> into the if statement: "{% if request.user.is_authenticated %}".
